### ISSUE TITLE
Pro version / how to detach the license to migrate to a new macbook ? 

### ISSUE THREAD

**Issue by gfrog73** [rugarciap/Turbo-Boost-Switcher#100]
I've the pro version 2.8.0, and I want to replace my macbook. 
How can I detach the license from the actual macbook, to be sure that I can re-install to the new one ? 

Thanks for your help

**Comment by rugarciap** [comment]
Hi, this is a support question.., not an issue with the app. You can write to the email inbox displayed within the app.

Closing.
