### ISSUE TITLE
Not working on 16-inch Macbook Pro?

### ISSUE THREAD

**Issue by forrestal** [rugarciap/Turbo-Boost-Switcher#105]
Just testing the free version of the new 16-inch Macbook and seems like TBS isn't working.

Granted kext permissions but when trying to disable TB nothing happens. Restart and trying multiple times didn't work either. Did someone experience similar problems?

**Comment by rugarciap** [comment]
Hi! Please, reach me at my contact address (it's on the faqs at rugarciap.com) for support and gladly will answer there. This is for specific issues with the app.

Thanks!
