### ISSUE TITLE
Can’t turn off TB on OS X Catalina 

### ISSUE THREAD

**Issue by F3000** [rugarciap/Turbo-Boost-Switcher#106]
Hi , 

I can install theprogramm . All fine. I have also accepted the message in the settings view. 

When I click on the icon in the tab bar I can use all features , except turn off TB and tun on the setting „Start the program with OS X boot“ 

I use the free version on OS X 10.15.1 

I hope you can help me . Thanks

**Comment by rugarciap** [comment]
Hi! Please, write to the support account listed at faqs. This is for issues, not for support with the process of installing the app. Thank you for your understanding and by using the app!

Best.
