### ISSUE TITLE
Apple deprecating kernel extension 

### ISSUE THREAD

**Issue by kradalby** [rugarciap/Turbo-Boost-Switcher#109]
Hi

Just noticed this: https://developer.apple.com/support/kernel-extensions/

I guess this will affect this project?

**Comment by rugarciap** [comment]
Hi!

No, it doesn't (yet). There is no alternative API for the calls used by the kext included with Turbo Boost Switcher, so it's not deprecated yet. When the alternative becomes available, it will be migrated if possible.

There is a lot of confusion around this and many people believe (even recognised media and Apple magazines) next macOS release will deprecate kernel extensions. Well, that's not true. It will deprecate those with alternatives under system extensions framework, and only those.

In fact, the app works just fine on just released 10.15.4 beta without any warning..., and again, when the API becomes available, the kext will be migrated if Apple decides to make available the needed APIs.

_Kernel programming interfaces (KPIs) will be deprecated as alternatives become available_

And all of this is also confirmed by an Apple Engineer answering to one question I posted some days ago:

[https://forums.developer.apple.com/message/402764#402764](https://forums.developer.apple.com/message/402764#402764)
