### ISSUE TITLE
Does Turbo Boost Switcher disable kext signing?

### ISSUE THREAD

**Issue by vitorgalvao** [rugarciap/Turbo-Boost-Switcher#11]
[DisableTurboBoost.kext](https://github.com/nanoant/DisableTurboBoost.kext) seems to need to do it, so does Turbo Boost Switcher do so as well?

And if it does, does it stays off, or is it re-enabled every time we turn on turbo boost?

**Comment by AntuanKhanna** [comment]
@vitorgalvao when you run ```sudo nvram boot-args``` you can see that kext-dev-mode != 1, this may mean that Turbo Boost Switcher do not changing kext signing settings.

**Comment by vitorgalvao** [comment]
@AntuanKhanna That being the case, it would still be interesting to know how Turbo Boost Switcher does it. Thinking about it, what may be happening is that Turbo Boost Switcher is signed with an Apple Developer ID. WOuld like to know for sure, though.

**Comment by rugarciap** [comment]
HI!

Turbo Boost Switcher doesn't change the signing settings, in fact, since OSX El Capitan, the "nvram" trick doesn't work :(. What the app does is to change the file owner in order to be able to install the kext.

I've requested Apple permission so I can sign the kext file. Stay tunned!

Best.

**Comment by rrecio** [comment]
Any update on this?

**Comment by alexcanepa** [comment]
Ruben posted on his blog that Apple did not grant him a signature for the kext file. 
However, it's important to note that the app can be fixed in El Capitan by disabling its new "System Integrity Protection" from recovery boot with the command `csrutil disable`. 
You can check that this worked after rebooting with `csrutil status`. Disabling SIP also allows you to modify the EFI partition and make other low-level system modifications.

**Comment by vitorgalvao** [comment]
> Disabling SIP also allows you to modify the EFI partition and make other low-level system modifications.

And the feature exists exactly so this can’t happen, as a security measure. I really don’t get why people always talk about disabling security features as an exclusively good thing. These suggestions should come with tons of caveats and a thorough explanation of why it is undesirable. Lets not teach users to screw themselves without knowledge of the consequences.

Eitger way, I think the issue can be closed.
