### ISSUE TITLE
TB Boost behaving inconsistently after sleep+unlock

### ISSUE THREAD

**Issue by igor-makarov** [rugarciap/Turbo-Boost-Switcher#111]
Leaving this as a reply to #108 because I can't reply there for some reason.

The behavior I'm seeing seems strange, because:
* Entering the password like requested **removes the kext** and enables TB
* Pressing 'Cancel' leaves the **kext installed** and TB disabled

**Comment by rugarciap** [comment]
That's because I locked the conversation..., as answered there, kext needs to be reinstalled (if tb disabled) because Apple internally disables TB after some time sleeping. This has been the behaviour since first releases.

**Comment by igor-makarov** [comment]
But as far as I can see, it stays installed after canceling. I've been doing this for the past 3 days and it has been consistent.

The only reason I started doing it was because entering the password uninstalled the kext.

Entering the password should reinstall the kext, right?
