### ISSUE TITLE
Turn Off throws some strange error

### ISSUE THREAD

**Issue by fabicsp** [rugarciap/Turbo-Boost-Switcher#112]
I have installed it from binary, have followed all of your steps, and also have read the faq. 

os: 10.15.3 Catalina

When I have installed the app, just prompt up some dialog box for password but haven't had to allow it in **Security & Privacy**.
The app is builded fine with xcode **=>** dropped it in to the Applications folder **=>** started it **=>**
Prompt for a pw **=>** Done **=>** 
Trying to switch off the turbo boost, and getting the following sys log: 
`(com.apple.xpc.launchd.domain.pid.security_authtr.1040): Failed to bootstrap path: path = /usr/libexec/security_authtrampoline, error = 108: Invalid path`

```
Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_MEMORY_ERROR at 0x0000000100002df0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [1927]
```

(Also have install - reinstall, reboot several times)

**Comment by rugarciap** [comment]
Hi! 

The app works fine with all versions of Catalina, including the latest beta as of now (10.15.4 beta 5). If you're still having issues installing and running the app, you can reach me at my email address (rugarciap.com/faqs .. at the end ;) for support!

Best!
