### ISSUE TITLE
Any way to enable/disable via shell?

### ISSUE THREAD

**Issue by dzg** [rugarciap/Turbo-Boost-Switcher#115]
Anyone know a way to control Turbo Boost from command line?

**Comment by rugarciap** [comment]
You can load the kernel extension using kexutil

Best!

**Comment by varenc** [comment]
For reference for others, to load the kext and disable turboboost:

```
sudo kextload "/Applications/Turbo Boost Switcher Pro.app/Contents/Resources/DisableTurboBoost.64bits.kext"
```

And to unload it, re-enabling turbo boost:
```
sudo kextunload "/Applications/Turbo Boost Switcher Pro.app/Contents/Resources/DisableTurboBoost.64bits.kext"
```

Assuming you've already got Turbo Boost Switcher installed and working and the kext approved!

**Comment by andiradulescu** [comment]
In 2024 I'm using this command to disable turboboost:
```
sudo kextload "/Applications/tbswitcher_resources/DisableTurboBoost.64bits.kext
```
This one to re-enable turboboost:
```
sudo kextunload "/Applications/tbswitcher_resources/DisableTurboBoost.64bits.kext"
```
And this one to see the status:
```
kmutil showloaded -V release | grep -c com.rugarciap.DisableTurboBoost
```

To troubleshoot any errors check HELP.rtfd from the dmg or run this command:
```
sudo kextutil -v /Applications/tbswitcher_resources/DisableTurboBoost.64bits.kext
```
