### ISSUE TITLE
Multiple processes running at max cpu

### ISSUE THREAD

**Issue by ddaddy** [rugarciap/Turbo-Boost-Switcher#116]
On my MBP i've come across a situation a few times were I have Turbo Boost disabled but the fans are going crazy. In Activity Monitor it shows 2 or 3 processes of Turbo Boost Switcher all running at 95%+ cpu.
If I Quit TBS from the task bar, the processes still run. I have to force close them from Activity Monitor for things to start settling down.

**Comment by rugarciap** [comment]
2 o 3 processes..., please, be more specific, attach logs, screenshots, steps to reproduce.., etc

Besides... the app doesn't launch multiple processes nor makes any kind of CPU intensive task. You can also write to my contact address (detailed at faqs at rugarciap.com ) for support about how to properly install and run the app if you're still unable to get it to work with the info shown there.

Best!

**Comment by ddaddy** [comment]
I have it running fine on my iMac and it runs fine most of the time on MBP. It seems that after a few days of not restarting the MBP it starts to happen and I end up with multiple instances. I have multiple users using the MBP so I wonder if that's part of the issue.
I'll take a screenshot next time. What logs would I be looking for?

**Comment by ddaddy** [comment]
I just had this again. It's running at really high CPU and fans going crazy. I force quit it from Activity Monitor, but the toolbar icon and menu where still there.
Where can I get logs from?

<img width="759" alt="Screenshot 2020-05-20 at 19 51 38" src="https://user-images.githubusercontent.com/1425808/82486147-5bac8a80-9ad4-11ea-8fd6-03b388f22bc3.png">
