### ISSUE TITLE
Pro Version of TBS does not disable Turbo boost

### ISSUE THREAD

**Issue by vstoppe** [rugarciap/Turbo-Boost-Switcher#118]
I just bought Turbo-Boost-Switcher. Unfortunately I have a big problem. It does not disable the turbo boost:
- already rebooted.
- The menu application starts 
- but the kext is not loaded: "kextstat | grep -i turbo" gives no output
- In the menu app "Disable Turbo boost" is grayed out.

If I start the free version of TBS everything works ok. It aks annoyingly for the password and then loads the kext, which I can verify with "kextstat | grep -i turbo"

I am running macOS 10.15.4 and a MBP 16 2019.

This log file is all what I could get from macos:
https://pastebin.com/raw/4Lw5Wwpw

If you tell me how, I will provide more diagnostic information.

**Comment by rugarciap** [comment]
Hello,

No worries, the app works fine with all Intel macbooks.., but this is a support question, nor issue with the app so please, write to the address provided on Gumroad receipt so I can help you.

Best regards.
