### ISSUE TITLE
Kernel Panic when Disabling Turbo Boost

### ISSUE THREAD

**Issue by gothickitty93** [rugarciap/Turbo-Boost-Switcher#119]
I just did a new install of the app, and when I selected to disable turbo boost, my system panicked.

Log is here: [https://pastebin.com/AYVkp5KT](url)

**Comment by rugarciap** [comment]
Hello,

Mac mini model used (Macmini8,1 ) is the only Mac model that doesn't has Turbo Boost Intel feature.., you can't use the app nor the kext on it.

**Comment by gothickitty93** [comment]
ugh. i feel silly. Thanks!
