### ISSUE TITLE
2.9.1

### ISSUE THREAD

**Issue by Maddy16194** [rugarciap/Turbo-Boost-Switcher#120]
Not able to Install, Says the app is broken.
![Screenshot 2020-05-10 at 4 27 53 AM](https://user-images.githubusercontent.com/15812200/81486980-c230dd80-9276-11ea-8d29-e1623f05ace3.png)

**Comment by rugarciap** [comment]
Hi,

Where did you get the binary from? it says you've downloaded it from github.., but the binary is hosted at Amazon S3... try downloading again from the link at readme.
