### ISSUE TITLE
I purchased pro but reset my laptop, how do I re-download?

### ISSUE THREAD

**Issue by rgaufman** [rugarciap/Turbo-Boost-Switcher#122]
Hi there,

I purchased pro from https://gumroad.com/ but haven't received any email confirmation or invoice and now I am struggling to re-download.

It does show up in my bank:
<img width="616" alt="Screenshot 2020-05-16 at 22 03 25" src="https://user-images.githubusercontent.com/33842342/82130241-7e336080-97c1-11ea-86c9-04c66143ce51.png">

Can you please help?

EDIT: I see similar type questions and saying to reply to the receipt email or to the email in the app, I didn't receive the receipt email and I cannot find an email in the app. Please help.

**Comment by rugarciap** [comment]
Please, write to the email address shown at https://rugarciap.com/faqs for support including the email account you used to get the pro version and/or your key. You can also check your spam folder just in case. This is for issues with the app, not for support. Thanks!
