### ISSUE TITLE
Will this app still work with the next version of macOS? Version 10.16?

### ISSUE THREAD

**Issue by Evertt** [rugarciap/Turbo-Boost-Switcher#124]
I don't remember exactly where I found out that this app exists, probably from a youtube video from somebody like [Snazzy Labs](https://www.youtube.com/channel/UCO2x-p9gg9TLKneXlibGR7w), but it could've also been a blog post somewhere, I don't know.

In any case, I do remember that the dude casually mentioned that this app probably wouldn't work in the next version of macOS, since that next version would most likely not allow the kernel to be extended in the way that this app needs in order to function. I have no idea if this dude was speaking from knowledge, or if they were just guessing.

I'd like to hear from @rugarciap and whoever else is closely involved in the making of this app, is this true? And is it true for both the free version of this app *and* the paid version?

So far I've been using the free version, since it works well enough for my purposes. And I'm willing to pay for the paid version, but only if indeed the free version will stop working soon (since the next macOS is right around the corner) and the paid version will continue to work.

**Comment by Evertt** [comment]
Oh sorry, I did do a search for whether this question was asked before, but I had only searched in the open issues. And just now I also searched in closed issues and found #109. So I guess this question is a duplicate of that.

So if I understand [your comment](https://github.com/rugarciap/Turbo-Boost-Switcher/issues/109#issuecomment-583572558) correctly, there's nothing to worry about and this app will surely keep working for the foreseeable future, right? In that case I'll close this issue again. 😅

**Comment by rugarciap** [comment]
HI there!

Yes! that was already answered.., but nobody can be sure 100% percent about Apple, so who knows if they keep their word or not! will see when first 10.16 beta appears ;)

**Comment by Evertt** [comment]
@rugarciap so I bought the pro version and I have another question. I have a script called `setup.sh` on my laptop which I run every time I set up a new computer and it installs all my apps and restores my configuration etc.

One part of that script was `brew cask install turbo-boost-switcher`, but now that I have the pro version I want to find a way to install the pro app with the command line, since it doesn't seem to be available in brew. Do you have a one-liner for that?
