### ISSUE TITLE
kernel panic 

### ISSUE THREAD

**Issue by legendragonflyz** [rugarciap/Turbo-Boost-Switcher#129]
hi there. wanted to report this crash I have encountered a few times when I wake the computer from sleep after unplugging it. this is after I have disconnected the laptop from power and opened it on my lap, and TB switcher is configured to disable turbo boost when using battery power. using latest Catalina on a MBP 16. hope this helps! and if it something I can configure to solve on my end, please let me know. thanks. 

panic(cpu 8 caller 0xffffff80101f24ed): Failed mbuf validity check: mbuf 0xffffff8751a07100 len -9 type 1 flags 0x2 data 0xffffff8751a071be rcvif en5 ifflags 0x8863
Backtrace (CPU 8), Frame : Return Address
0xffffffa7abf4baf0 : 0xffffff800ff1f5cd 
0xffffffa7abf4bb40 : 0xffffff8010058b05 
0xffffffa7abf4bb80 : 0xffffff801004a68e 
0xffffffa7abf4bbd0 : 0xffffff800fec5a40 
0xffffffa7abf4bbf0 : 0xffffff800ff1ec97 
0xffffffa7abf4bcf0 : 0xffffff800ff1f087 
0xffffffa7abf4bd40 : 0xffffff80106c27cc 
0xffffffa7abf4bdb0 : 0xffffff80101f24ed 
0xffffffa7abf4bf50 : 0xffffff80101f2e27 
0xffffffa7abf4bfa0 : 0xffffff800fec513e 

BSD process name corresponding to current thread: kernel_task
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19F101

Kernel version:
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Kernel UUID: 54F1A78D-6F41-32BD-BFED-4381F9F6E2EF
Kernel slide:     0x000000000fc00000
Kernel text base: 0xffffff800fe00000
__HIB  text base: 0xffffff800fd00000
System model name: MacBookPro16,1 (Mac-E1008331FDC96864)
System shutdown begun: NO

System uptime in nanoseconds: 346165788972606
last loaded kext at 343932422575650: com.rugarciap.DisableTurboBoost	0.0.1 (addr 0xffffff7f93ba2000, size 12288)
last unloaded kext at 343951640751241: com.rugarciap.DisableTurboBoost	0.0.1 (addr 0xffffff7f93ba2000, size 8192)
loaded kexts:
com.realtek.driver.!ARTL815XEthernet	1.0.20
com.avast.PacketForwarder	2.1
com.avast.FileShield	4.0.0
@filesystems.smbfs	3.4.3
>AudioAUUC	1.70
>usb.realtek8153patcher	5.0.0
>usb.!UHostBillboardDevice	1.0
@kext.AMDRadeonX6000	3.0.9
@kext.AMDRadeonServiceManager	3.0.9
>!AGraphicsDevicePolicy	5.2.4
@fileutil	20.036.15
@AGDCPluginDisplayMetrics	5.2.4
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.5f6
>AGPM	111.4.4
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>!AUpstreamUserClient	3.6.8
>AGDCBacklightControl	5.2.4
>BridgeAudioCommunication	6.70.7
>!A!IKBLGraphics	14.0.6
>!AThunderboltIP	3.1.4
>!ATopCaseHIDEventDriver	3430.1
>!AHIDALSService	1
>!A!ISlowAdaptiveClocking	4.0.0
>!AMuxControl2	5.2.4
>!AAVEBridge	6.1
>!A!ICFLGraphicsFramebuffer	14.0.6
>!AMCCSControl	1.14
>!ABridgeAudio!C	6.70.7
>!AGFXHDA	100.1.428
>!A!IPCHPMC	2.0.1
@filesystems.autofs	3.0
>BCMWLANFirmware4355.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
>!ABCMWLANBusInterfacePCIe	1
@filesystems.hfs.kext	522.100.5
@BootCache	40
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
>!AVirtIO	1.0
@filesystems.apfs	1412.120.2
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
>usb.IOUSBHostHIDDevice	1.2
>!UAudio	323.1
>usb.!UHub	1.2
@kext.AMDRadeonX6100HWLibs	1.0
@kext.AMDRadeonX6000HWServices	3.0.9
|IOAVB!F	850.1
>!ASSE	1.0
@!AGPUWrangler	5.2.4
@kext.AMDRadeonX6000Framebuffer	3.0.9
>!ABacklightExpert	1.1.0
>!AHIDKeyboard	209
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.5f6
>!AActuatorDriver	3440.1
>!AMultitouchDriver	3440.1
>!AInputDeviceSupport	3440.8
>X86PlatformPlugin	1.0.0
|IOSlowAdaptiveClocking!F	1.0.0
@kext.AMDSupport	3.0.9
|IO!BHost!CUARTTransport	7.0.5f6
|IO!BHost!CTransport	7.0.5f6
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
>!AGraphicsControl	5.2.4
@!AGraphicsDeviceControl	5.2.4
|IOAccelerator!F2	438.5.4
>!ASMBus!C	1.0.18d1
|IONDRVSupport	576.1
|IOGraphics!F	576.1
>IOPlatformPlugin!F	6.0.0d8
@plugin.IOgPTPPlugin	840.3
|IOEthernetAVB!C	1.1.0
@kext.triggers	1.0
>usb.cdc.ncm	5.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!ABCMWLANCore	1.0.0
>mDNSOffloadUserClient	1.0.1b8
>IOImageLoader	1.0.0
|IO80211!FV2	1200.12.2b1
>corecapture	1.0.4
|IOSkywalk!F	1
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSerial!F	11
>!AXsanScheme	3
>usb.!UVHCIBCE	1.2
>usb.!UVHCI	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
>!AThunderboltPCIDownAdapter	2.5.4
>!AThunderboltDPInAdapter	6.2.6
>!AThunderboltDPAdapter!F	6.2.6
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssDmac	3.0.60
>!A!ILpssI2C	3.0.60
>!AThunderboltNHI	5.8.6
|IOThunderbolt!F	7.6.1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!AKeyStore	2
>!UTDM	489.120.1
|IOSCSIBlockCommandsDevice	422.120.3
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|CoreAnalytics!F	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	7.0.5f6
|IO!BPacketLogger	7.0.5f6
|IOUSBMass!SDriver	157.121.1
|IOSCSIArchitectureModel!F	422.120.3
|IO!S!F	2.1
|IOUSBHost!F	1.2
>usb.!UCommon	1.0
>!UHostMergeProperties	1.2
>!ABusPower!C	1.0
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by rugarciap** [comment]
Hi there!

The panic is not being caused by Turbo Boost Switcher, neither any of its components. In fact, the report shows that the kernel extension included with the app was properly loaded and unloaded more than 37 minutes before the panic (all kernel extensions are always listed in kernel panics logs).

It seems it's being caused by a network interface issue as you can see in the log, may be something related with en5 inteface..., I had some issues like this in the past when experimenting with network drivers.

**panic(cpu 8 caller 0xffffff80101f24ed):** Failed mbuf validity check: **mbuf** 0xffffff8751a07100 len -9 type 1 flags 0x2 data 0xffffff8751a071be rcvif **en5** ifflags 0x8863

You can take a look at this too: https://forums.macrumors.com/threads/help-diagnosing-a-kernal-panic.1737219/

In the future, for issues with pro version of the app if any, please contact directly with support email given when getting the pro key.

Thanks for supporting and best regards!
