### ISSUE TITLE
Black icon not visible in dark mode

### ISSUE THREAD

**Issue by Owumaro** [rugarciap/Turbo-Boost-Switcher#13]
The black icon is still black when using Yosemite's dark mode, which makes it look like a blank space.

![turboswitchicon](https://cloud.githubusercontent.com/assets/5205295/9294295/9ba1788a-4449-11e5-87a2-e6b7a8fcc56c.png)

**Comment by bretello** [comment]
I solved this quite brutally: by inverting the icon.

Download the image here:
![icon](https://cloud.githubusercontent.com/assets/8560118/10490890/c53bc65e-72a3-11e5-904d-836a4e8b8097.png)

Go to Turbo Boost Switcher.app/Contents/Resources/, make a copy of icon.png and replace icon.png with the image above. Close and re-open Turbo-Boost-Switcher

Result:
![screen shot 2015-10-14 at 6 46 18 pm](https://cloud.githubusercontent.com/assets/8560118/10490922/e337b924-72a3-11e5-9a6c-adf2ef95e1ff.png)

**Comment by rugarciap** [comment]
Thanks!, this has already been fixed for the next version.

Best!
