### ISSUE TITLE
TurboBoost Toggler issue

### ISSUE THREAD

**Issue by jozpac** [rugarciap/Turbo-Boost-Switcher#130]
Hello everybody,

I am trying to disable TurboBoost on my Macbook Air 2020 (MacOS Catalina the newest version). When I click on the "Disable Turbo Boost", nothing happens. Sometimes it asks me for password, but still nothing happens even if I enter my password correctly. The same thing happens when I try to check "Open at Login" checkbox - nothing happens. Any advices for how to fix this problem, please?

Thank you for your willingness.

**Comment by rugarciap** [comment]
Hello,

The app works fine with all Intel Macs having Turbo Boost and macOS releases including recently released Big Sur developer beta. I've you need support, write to the contact address available at rugarciap.com.. This is for issues/bugs/new features in the app.

Thanks!
