### ISSUE TITLE
can't allow 

### ISSUE THREAD

**Issue by mc9625** [rugarciap/Turbo-Boost-Switcher#131]
On My Macbook 12 with High Sierra (10.13.6) I can't allow the execution of Turbo Boost Switcher.

Even if I click on "allow" on the security panel nothing happen. I have even open the lock on the bottom left corner but didn't help.

**Comment by rugarciap** [comment]
Hello,

The app works fine with all Intel Macs having Turbo Boost and macOS releases including recently released Big Sur developer beta. I've you need support, write to the contact address available at rugarciap.com.. This is for issues/bugs/new features in the app.

Thanks!
