### ISSUE TITLE
Reports wildly innacurate CPU temperature?

### ISSUE THREAD

**Issue by rw3iss** [rugarciap/Turbo-Boost-Switcher#134]
Hello,
 I've been using the app for a day now, but it seems the CPU temperature is always wrong, but about 20 degrees!
 
See screenshot here:

<img width="511" alt="Screen Shot 2020-07-23 at 9 11 05 PM" src="https://user-images.githubusercontent.com/372120/88352787-09345800-cd29-11ea-9dd4-2eec3d274c67.png">

Notice the overlay shows 60 degrees, but the menu bar icon up to the right next to it (Macs Fan Control app) shows 78 degrees. Then also notice that the command line 'powermetrics' program running in the terminal that, also shows ~80 degrees.

Why does the Turbo Boost app always seem to show a 20 degree difference in the CPU temperature??

**Comment by rugarciap** [comment]
Hi,

The app uses the SMC Apple API to retrieve the CPU sensor temperature, you can take a look to the code.

There are a lot of sensors on a Mac, and can't speak by any other app.., In any case, there is also an enhancement pending to be released to monitor individual CPU sensors, I guess that might be the case.

Thanks for the info and will use while developing that feature for sure.

Best!

**Comment by rw3iss** [comment]
Cheers!
