### ISSUE TITLE
MacOs 10.15.6 keeping asking for code although I have pro version

### ISSUE THREAD

**Issue by NathanP1403** [rugarciap/Turbo-Boost-Switcher#136]
hi, 
the app keeps asking for password, and even after I entered it, it doesn't disable TB or turning it on.
I installed and dragged the .app to application folder and still nothing
I purchased the pro version ( your app is incredible btw !!) which is supposs to remember the password
I tried to remove it and reinstall it, reboot the os and still same thing
I would like to know what's wrong...
(again, I loved your app... keep the Mac cooler and keeps a lot of battery !)
thanks

**Comment by rugarciap** [comment]
Please, for support of pro version contact with the address given when getting the pro key, or just answering to the Gumroad receipt.

Thanks.
