### ISSUE TITLE
macos 10.15.6 can't use.

### ISSUE THREAD

**Issue by crab21** [rugarciap/Turbo-Boost-Switcher#137]
version:2.9.1
macos 10.15.6
can't use turbo boost switcher.

Looking forward to your reply.

**Comment by mimundome** [comment]
Same issue, it show it is running in activities monitor but I could not see the control options on the menu bar. Please advise how to fix it.

**Comment by rugarciap** [comment]
Hello, contact support address for help installing and running the app. It's all in the blog.

Thanks!
