### ISSUE TITLE
one issue and one request

### ISSUE THREAD

**Issue by cridemichel** [rugarciap/Turbo-Boost-Switcher#138]
Dear rugarciap,
first of all thank you very much for this very cool app, whose pro version I have just purchased!
On my macbook pro 16" i9 with Catilina 10.15.6, I noticed that if I set the upper threshold for fan speed to 2000 rpm in auto mode settings, the lower threshold (used to re-enable Turbo Boost) can not be higher than 1600 rpm, but minimum speed of my fans is something around 1800 rpm. Moreover, I think it could be useful to have the possibility to disable the turbo boost mode when temperature is higher than a preset (e.g. 70 C) value and re-enable it when the temperature is lower than another preset value (e.g. 55 C), since temperature rises faster than fan speed and this way one could prevent fan speed to increase significantly in auto mode. Indeed, if I set the upper fan speed threshold to something around 2400 rpm (to have a lower threshold around 1900 rpm), when fan speed is above 2400 rpm, your app switch off the Turbo Boost mode but this happens to be too late, in that CPU temperature is already very high and fan speed keeps increasing reaching its max (annoying) value,
 
best Cristiano

**Comment by rugarciap** [comment]
HI!

Thanks for supporting! Please, for pro questions, reach me at the email given in the Gumroad receipt. 

In any case, CPU temp mode will come in future versions, and regarding rpm threshold, the gap is set on purpose, since if it's too small, then TB gets constantly enabled/disabled depending on the CPU load. That's why I've set a 20% minimum gap between values.

Best!

**Comment by cridemichel** [comment]
> HI!
> 
> Thanks for supporting! Please, for pro questions, reach me at the email given in the Gumroad receipt.
> 
> In any case, CPU temp mode will come in future versions, and regarding rpm threshold, the gap is set on purpose, since if it's too small, then TB gets constantly enabled/disabled depending on the CPU load. That's why I've set a 20% minimum gap between values.
> 
> Best!

ok, thank you for the prompt reply, looking forward to having a future version with CPU temp mode. 
Btw, is there any release date?
