### ISSUE TITLE
Cannot disable Turbo Boost on free version on Catalina 10.15.6

### ISSUE THREAD

**Issue by stephenchu** [rugarciap/Turbo-Boost-Switcher#139]
I did see in Console.app the following log lines when I tried to click "Disable Turbo Boost" on TBS v2.9.1 (Catalina 10.15.6):

```
AuthorizationExecuteWithPrivileges and AuthorizationExecuteWithPrivilegesExternalForm are deprecated and functionality will be removed soon - please update your application
Succeeded authorizing right 'system.privilege.admin' by client '/usr/libexec/security_authtrampoline' [36603] for authorization created by '/Applications/Turbo Boost Switcher.app' [36487] (3,0) (engine 5196)
```

🙏

**Comment by rugarciap** [comment]
Hi!

Please, for support about how to run the app, problems installing, etc. just write to the support address shown at rugarciap.com.., or left a comment there so I can reach you.

Best!
