### ISSUE TITLE
Impossible to download pro version when already paid a license

### ISSUE THREAD

**Issue by jimblue** [rugarciap/Turbo-Boost-Switcher#142]
Hello,

I've clean install my Mac and reinstall Turbo Boost Switcher.
I didn't loose my license number but there is no input on Turbo Boost Switcher to unlock pro version.
So I've look to directly download the pro version on your website and Gumroad but wasn't able to find the link.

Thank you for your help.

**Comment by rugarciap** [comment]
Hi,

Please, reach me by answering to the Gumroad receipt and/or at the email address provided with the receipt.

Thanks!
