### ISSUE TITLE
Impossible to download pro version when already paid a license #2

### ISSUE THREAD

**Issue by jimblue** [rugarciap/Turbo-Boost-Switcher#143]
Sorry but as there is no contact form on your website or even your email that's why I'm using Github issue. And because you locked my first issue I'm force to create a new one now.
It's the only way to contact you as the email on the receipt is the Gumroad email, not yours... And Gumroad policies are saying that I have to contact the seller.

**Comment by rugarciap** [comment]
Hi,

Just reply to the receipt, it will arrive to my email address. You can also contact to the email included on the receipt.., the text below the button to download the binary includes an adress where you can also reach me.

The blog at rugarciap.com includes a contact address at the faqs, there is also the option to comment on the blog and you can even reach me on twitter.

Github is for the free version and this section to report issues related to it. For support on pro version, you can reach me on any of the multiple ways detailed above.

Regards.

**Comment by jimblue** [comment]
ok thanks, just found your email on at the FAQ bottom.
I've just send you an email. (sorry that I use Github, your email is really hard to found, you should put it in the contact page.)
