### ISSUE TITLE
OS X Bigsur Beta8 crashes after launching TBS

### ISSUE THREAD

**Issue by F3000** [rugarciap/Turbo-Boost-Switcher#145]
Installed is public Beta 8 from Big Sur . 

TBS is in version 2.9.1 

Steps to reproduce :

- restart the Mac 
- in the Pop up for the admin rights -> fill in your password 

- after that the Mac crashes and restart

**Comment by rugarciap** [comment]
Hi,

The app and kext works fine with beta 8, both free and pro version. Just tested all scenarios and updated compatibility post at rugarciap.com

May be you're using a Mac without Turbo Boost feature? could you please attach some logs?

In any case, for additional support, please, reach me at my contact address detailed at rugarciap.com , twitter, blog, etc.

Thanks!
