### ISSUE TITLE
Turbo Boost Switcher not working with 10.15.7

### ISSUE THREAD

**Issue by aufuk1** [rugarciap/Turbo-Boost-Switcher#147]
Hello,
Turbo Boost Switcher not working after 10.15.7 update.

I wonder what can I do about it.

**Comment by rugarciap** [comment]
Hi,

The app works fine with that version. This is a support question, not an issue with its corresponding steps to reproduce, logs, etc. If you wish you can reach me through other contact methods as described in the blog faqs.

Best.
