### ISSUE TITLE
Disable Turbo Boost not working in Big Sur

### ISSUE THREAD

**Issue by thejhh** [rugarciap/Turbo-Boost-Switcher#151]
Hi!

I have the paid Turbo Boost Switcher Pro and Turbo Boost no longer works on my system.

It was working fine until I had a strange problem -- the keyboard stopped working and had to forcefully shutdown my OSX. Probably not related to the problem though. After reboot, the Turbo Boost Switcher Pro does start, but nothing happens when I try to disable Turbo Boost.

I already tried to reinstall as instructed in the help. Same continues. The software starts successfully -- but cannot disable Turbo Boost.

**Comment by thejhh** [comment]
My problem was solved by running `kmutil trigger-panic-medic` in the Recovery Mode as instructed in the [FAQ](https://www.rugarciap.com/faqs/).

**Comment by pjo336** [comment]
Just wanted to say this fixed mine as well, thanks for looping back and posting the solution @thejhh
