### ISSUE TITLE
Where to enter license key?

### ISSUE THREAD

**Issue by FrEaK-git** [rugarciap/Turbo-Boost-Switcher#152]
Hey... i recently buyed the pro version... now i've done a fresh and clean install of macOS and installed Turbo-Boost-Switcher again... and i want to get the pro version back... how? Only thing i have is a license key... and no option to enter it anywhere... :-(

**Comment by rugarciap** [comment]
Hi!

This is not for pro support. Please, write to the inbox detailed on Gumroad receipt. In any case, from there (Gumroad's receipt at your inbox) you can click over the "view content" button to download the binary at anytime.

Thanks for supporting and best regards!
