### ISSUE TITLE
Turbo Boost Switcher Pro is not working anymore on Big Sur. 

### ISSUE THREAD

**Issue by saimonh3** [rugarciap/Turbo-Boost-Switcher#154]
Note: I'm using the latest version v2.10.1

**Comment by rugarciap** [comment]
Hi,

The app works fine with Big Sur since the first beta. Please, follow the steps included with the HELP file to troubleshoot the install, and if that still doesn't fix the install, contact me directly to the address detailed there.

Thanks for supporting and best regards.
