### ISSUE TITLE
Which cpu temp is used in Turbo boost switcher pro?

### ISSUE THREAD

**Issue by ShayanYaseen** [rugarciap/Turbo-Boost-Switcher#155]
I am considering purchasing the pro version to disable turbo boost based on the CPU temperature. However since the free version does not track the die temperature (apparently taking the first temp value from smc) will the pro version do the same ?

Since die temperature and core temperature can be largely different in both value and time to variate (with me personally inclined to use die temperature ) , could you specify which value is being used by the pro version to disable turbo boost based on temperature. Also if the app is still taking the first value could there be an option to specify which temp to use . 

(The mac fan control already allows the user to set the fans based on several senors CPU - core , die etc.) 

Currently the free version of turbo boost is showing me 59C while the diode temp of my CPU is 68 a staggering 9C difference

**Comment by rugarciap** [comment]
The app shows the cpu core temperature using the SMC Api.., and there is a feature request #55 open to add individual core sensors.., that will be accomplished sometime on a future version.

You can add this there.

Thanks!
