### ISSUE TITLE
Admin credentials unnecessarily requested after sleep

### ISSUE THREAD

**Issue by Atemu** [rugarciap/Turbo-Boost-Switcher#161]
Hi, whenever my MBP2018 wakes up from sleep, TBS asks for an admin password eventhough turbo boost is still disabled.

I have unchecked "Open at login" and "Disable TB on start" but it still prompts me for credentials after every sleep.

**Comment by panruza** [comment]
Same with me...

**Comment by Atemu** [comment]
FYI I fixed this by just running TBS as admin by default as described here:

https://github.com/rugarciap/Turbo-Boost-Switcher/issues/4#issuecomment-398014403
