### ISSUE TITLE
Can't Disable Turbo Boost in macOS Mojave

### ISSUE THREAD

**Issue by armdn** [rugarciap/Turbo-Boost-Switcher#162]
I've upgraded from macOS High Sierra (where Turbo Boost Switcher works correctly) to macOS Mojave, and it stopped to work.

Reinstallation did not solve the problem.

Application started, password asked and after entering the password - nothing happening.

**Comment by rugarciap** [comment]
Hi,

The app works fine with all macOS versions released so far, including last Big Sur release. Please, check the howto/help file included with latest version and if that doesn't help, feel free to reach me for support by email using the address described on that file.

Best!
