### ISSUE TITLE
turbo boost switcher pro not working with Big Sur 11.4

### ISSUE THREAD

**Issue by cridemichel** [rugarciap/Turbo-Boost-Switcher#163]
Dear Developer,
I purchased Turbo Boost switcher pro and I consider it of invaluable usefulness.
However, after I have upgraded my macbook pro 16" to Big Sur 11.4 turbo boost switcher stopped working probably, i.e. the app starts regularly but you can't disable turbo boost mode. I think this is because turbo boost switcher kernel extensions are incompatible with latest version of OSX. Indeed, virtual box stopped working due to an issue related to kernel extensions. Are you planning to fix this soon? Is it an easy fix?

best Cristiano

**Comment by samtstern** [comment]
I am experiencing the same issue.

**Comment by rugarciap** [comment]
HI!

Just reboot! :) More info at the faqs https://www.rugarciap.com/faqs/ 

Best!

**Comment by cridemichel** [comment]
oh that simple! it works now, thank you!

best C.

Cristiano De Michele
***@***.***

**Comment by KatsuShooter** [comment]
@rugarciap I have the same issue, but restarting doesn't help. MBP 16, Big Sur 11.4

**Comment by rugarciap** [comment]
For additional support you can reach me at the address included within the faqs and/or the help file. You can try also the steps provided there to rebuild kext caches.
