### ISSUE TITLE
AutoConfig by CPU Temp Using CPU Proximity 

### ISSUE THREAD

**Issue by QAUser777** [rugarciap/Turbo-Boost-Switcher#167]
It looks like the Turbo Boost’s automatic enable/disable configuration when based off of CPU temperature uses the reading of ‘CPU Proximity’ on 2017 iMac 27". This is a poor reading to use for a feature like that. CPU proximity is not a sufficient reading for CPU temperature. It would be so much better if this ran off of the temperature for CPU Core Average or the CPU PECI. This issue really makes the auto configuration based off of CPU Temp kind of useless since CPU proximity will only go up very marginally when there is high CPU usage. For instance, fluctuating between 10% - 100% CPU usage will only make  CPU proximity range from 50-62 degrees celcius. No sure if this is the same for MacBooks 

Feature is sadly useless for my machine :(

**Comment by rugarciap** [comment]
Hi!

Thanks for your feedback! The app uses SMC Api to get CPU core temp readings. In any case, there are a lot of sensors and indeed in the future, and if I can, I plan to include more sensor readings within the app than can of course be used on auto modes.. but can't promise when!

Thanks again and best regards.
