### ISSUE TITLE
Does not work on mac big sur 11.4， Error Domain=KMErrorDomain Code=31 

### ISSUE THREAD

**Issue by midaug** [rugarciap/Turbo-Boost-Switcher#168]
sudo /Applications/Turbo\ Boost\ Switcher.app/Contents/MacOS/Turbo\ Boost\ Switcher

Defaulting to kernel file '/System/Library/Kernels/kernel'
Executing: /usr/bin/kmutil load --bundle-path /Applications/tbswitcher_resources/DisableTurboBoost.64bits.kext
Error Domain=KMErrorDomain Code=31 "Error occurred while building a collection: in '/Library/StagedExtensions/Library/Extensions/endpointKbase.kext/Contents/MacOS/endpointKbase' missing __TEXT segment" UserInfo={NSLocalizedDescription=Error occurred while building a collection: in '/Library/StagedExtensions/Library/Extensions/endpointKbase.kext/Contents/MacOS/endpointKbase' missing __TEXT segment}

**Comment by rugarciap** [comment]
Hi,

The issue is not with the app extension, is with another one: **endpointKbase.kext**

macOS doesn't rebuild kext cache if any extensions fails to load, and that one has some issues as you can see in the log.

Best.

**Comment by midaug** [comment]
I am not sure about the purpose of endpointKbase.kext, it appeared after upgrading to big sur 11.4
