### ISSUE TITLE
Always getting sudo window after wakeup

### ISSUE THREAD

**Issue by NinoFloris** [rugarciap/Turbo-Boost-Switcher#17]
I don't really know why it does this, when I click it away 3 times turboboost still stays off?
Could you recheck the state and if the state did not change don't ask for credentials?

As I can imagine after a few hours your authenticationRef has been expired by the auth server.

Thanks for the tool though! It's great and allows my energy hungry, late 2011, (first 45W TDP model, quad core)  to stay silent much more easily. And all while I don't notice the difference one bit.

It even stays around 50 degrees when I'm running a VM!

**Comment by rugarciap** [comment]
Yes, the auth expires since OSX uses a System Privileges caché. This can we worked around by running the app as root (check out the README file).
