### ISSUE TITLE
Even after reboot Turbo Switcher doesn't work on 11.15.1

### ISSUE THREAD

**Issue by slavag** [rugarciap/Turbo-Boost-Switcher#173]
![image](https://user-images.githubusercontent.com/511540/132262305-a9f1398f-179f-437e-9e12-a8f1ffbb762e.png)

Please see the video, I did a reboot , twice

https://user-images.githubusercontent.com/511540/132262290-1ae1abe2-5dd4-4ee6-96c7-940b651965db.mov

Please advise.

**Comment by rugarciap** [comment]
Hi,

Help file includes several workarounds for this kind of issues. Please, make sure you try them and, if keeps not working, you can reach me at the email address detailed there for additional support.

Best.
