### ISSUE TITLE
Disable Turbo Boost Not Working On Pro Version

### ISSUE THREAD

**Issue by theArtechnology** [rugarciap/Turbo-Boost-Switcher#177]
```
Model Name: MacBook Pro
Model Identifier: MacBookPro16,2
Processor Name: Quad-Core Intel Core i5
Processor Speed: 2 GHz
Number of Processors: 1
Total Number of Cores: 4
L2 Cache (per Core): 512 KB
L3 Cache: 6 MB
Hyper-Threading Technology: Enabled
Memory: 16 GB
Boot ROM Version: 1715.40.15.0.0 (iBridge: 19.16.10549.0.0,0)
```
Using version 2.11.0 of the dmg.

When pressing Disable Turbo Boost Nothing happens + when I see the graph, it stays on Enabled (with the orange line)

**Comment by rugarciap** [comment]
Hi!

The app works fine with all versions of macOS released so far, so please, take a look to the help included for troubleshooting and if still unable to disable don't hesitate to reach me directly on email.

Thanks!

**Comment by theArtechnology** [comment]
Thanks. Fixed it with: 

```
sudo kextcache --clear-staging
```

The issue was that permission problem:
```
Diagnostics for /Applications/tbswitcher_resources/DisableTurboBoost.64bits.kext:
Authentication Failures: 
    File owner/permissions are incorrect (must be root:wheel, nonwritable by group/other): 
        /Library/StagedExtensions/Applications/tbswitcher_resources/DisableTurboBoost.64bits.kext
        Contents
        MacOS
        DisableTurboBoost
        Info.plist~
        Info.plist
```

I leave that here for other users if they encounter the same issue.

**Comment by rugarciap** [comment]
Great! thanks for letting me know. This is already included in the help file, so great!

Best!
