### ISSUE TITLE
Jan 2022 macOS update breaks switching

### ISSUE THREAD

**Issue by berezovskyi** [rugarciap/Turbo-Boost-Switcher#179]
After the yesterday update to 11.6.3 (20G415), TBS Pro is no longer able to disable TB. Does it happen to others?

**Comment by rugarciap** [comment]
Hi,

This is explained on other issues. Please, just reboot..., Big Sur requires you to make another reboot after updating to rebuild kext user permission database.

**Comment by rugarciap** [comment]
Great! glad to help :).
