### ISSUE TITLE
Laptop is completely discharged overnight

### ISSUE THREAD

**Issue by RMatushkin** [rugarciap/Turbo-Boost-Switcher#180]
Hi!
Explain to me why my laptop is completely discharged overnight?
Could this be due to disabled turbo boost?
How can I fix it and my laptop will go to “sleep”? 😄

MBP 16” 2019, Monterey.

**Comment by rugarciap** [comment]
Hi,

This is not for support, it's for openning issues / bugs with the open source version of the app. In any case, it could bee any app that uses Power Nap feature to do tasks in the background while sleeping. I suggest you to disable that.
