### ISSUE TITLE
Not working on MBP 16 2019 with macOs Moneterey 12.4

### ISSUE THREAD

**Issue by dennispidun** [rugarciap/Turbo-Boost-Switcher#181]
I've tried everything to make this work like restarting several times, reinstalling the app, trying the hotkeys instead of pressing the buttons. It seems like, that it has no effect, whatever I do. Is this a known problem or am I doing it maybe wrong?

**Comment by rugarciap** [comment]
Hi,

The app works fine both free and pro with all macOS versions released so far, including current macOS beta. Please, for support, you can follow the troubleshooting guide included with the app and if this not works, reach me at the contact included for help and support.

Best!
