### ISSUE TITLE
Issue: Editable about section

### ISSUE THREAD

**Issue by fd1911** [rugarciap/Turbo-Boost-Switcher#183]
The about menu in wich includes text regarding license and usage of the application is not read only and is editable.
I can write anything I want there.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/50965810/193066055-7eb07afd-0f82-4e47-ba58-034fabba59ef.png">

The help section works as intended, read only.

Willing to contribute and make a PR but honestly dont know to change it from the source code.

**Comment by rugarciap** [comment]
Hi, this has been addressed on 2.12.0 version. Best!
