### ISSUE TITLE
Feature Request: Apple silicon low-power mode

### ISSUE THREAD

**Issue by restfuladi** [rugarciap/Turbo-Boost-Switcher#187]
Apple silicon has a low-power mode option that seems to cap the M1 Max ~2.5 Ghz (not sure about the other variants). This greatly reduces max temps and noise at full CPU utilization on my 14" MBP, from ~95C with fan at 100% to ~75C with fan at ~70%. Unfortunately it also caps the display refresh rate to 60hz, and the toggle is buried in System Preferences, Battery, Battery/Power Adapter. It would be ideal nice if TBS could automatically toggle only the CPU throttle for quieter parallel processing, but even the full mode would really convenient.

Thanks!

**Comment by rugarciap** [comment]
Hi!

Thanks for your feedback! Released some months ago another tool (with also free and pro version) called Power Mode Switcher you can try: [www.pmswitcher.com](http://www.pmswitcher.com).

There is a lot of room of improvement yet, and of course this would fit nicely there too!

Feel free to post any feedback at anytime, it's very welcome :)

**Comment by restfuladi** [comment]
> Hi!
> 
> Thanks for your feedback! Released some months ago another tool (with also free and pro version) called Power Mode Switcher you can try: [www.pmswitcher.com](http://www.pmswitcher.com).
> 
> There is a lot of room for improvement yet, and of course this would fit nicely there too!
> 
> Feel free to post any feedback at anytime, it's very welcome :)

I didn't know you had an Apple Silicon version. I already bought TBS Pro but I'd be open to buying this if auto mode had a temperature, power, or CPU% option. My main use case is reducing heat and noise during high load.

**Comment by rugarciap** [comment]
That auto modes will come in the near future, as soon as I get an M1 / M2 for myself!
