### ISSUE TITLE
Install back after timemachine

### ISSUE THREAD

**Issue by kunpoolsion** [rugarciap/Turbo-Boost-Switcher#192]
Hi,
TBS lover here.
I was in need of reinstall and recover from timemachine.
I can´t find the way to activate the pro version back.
Is not asking for the license, has no auto menu and is asking for admin pass on every reboot and awake.
Any advice in how to fix it?
Thanks

**Comment by rugarciap** [comment]
Hi there!

Please, Github is intended only for issues with the open source version, not for supporting. 

In any case, if there is no auto mode menu option, then it means you're using the free binary, that doesn't contain it. You need to download the pro specific binary by clicking over the view content / download button included with your Gumroad receipt.

Best!
