### ISSUE TITLE
How do I reinstall the Pro version

### ISSUE THREAD

**Issue by kpturner** [rugarciap/Turbo-Boost-Switcher#193]
I have no idea where else I can log this question.  I bought the pro version many moons ago.  I now need to reinstall it, but I cannot get to any download page to get it without going through a purchase process.  I already have my licence code but there is nowhere for me to add it (I have installed the free version for now, but that doesn't have an option to upgrade or put in the licence code to "Go Pro").

Help!

**Comment by rugarciap** [comment]
Hi,

Inside the Gumroad receipt, there is a view content button to download the binary at anytime. You can also reach my by answering that email (just resent it to your account) and also another support email address you can use to reach me at anytime.

Best!
