### ISSUE TITLE
How to solve the problem that I need to enter the password every time?

### ISSUE THREAD

**Issue by myotsuki** [rugarciap/Turbo-Boost-Switcher#194]
![截屏2023-03-23 23 52 16](https://user-images.githubusercontent.com/54971922/227260494-d2cad0e4-1fef-4848-b51a-76f9bf2dbb62.png)

My system is Ventura and whenever I boot it requires me to enter a password to use it...

**Comment by rugarciap** [comment]
Hi,

This is answered here: https://www.rugarciap.com/faqs/

Best.
