### ISSUE TITLE
Pro 2.12.0 with lic key requires authorization since update.

### ISSUE THREAD

**Issue by tomaptx** [rugarciap/Turbo-Boost-Switcher#197]
Running macOS 13.3.1 (a) on MBP 2019. Recently did the update of TBS Pro to 2.12.0 and since then I am asked for the admin password and the icon that shows boost on/off seems to lag or be opposite of the actual state of turbo boost. The password is required each time on switching on/off as well as any wake from sleep or restart.

**Comment by rugarciap** [comment]
Hi,

Please, follow the steps provided inside the help, section 2.2.- The app asks for password over and over again

If this doesn't help, reach me directly at the support address on that document or just answer directly to the Gumroad receipt.

Best.
