### ISSUE TITLE
Turbo Boost Switcher Pro 2.9.1 won't update

### ISSUE THREAD

**Issue by dsihacker** [rugarciap/Turbo-Boost-Switcher#199]
I've been trying to update turbo boost switcher pro for a very long time, but when I push udpates, then download, the dmg doesn't appear anywhere in the downloads folder, or in the computer in general.

**Comment by rugarciap** [comment]
Hi,

Please, reach me at the support email included with the purchase, or answering the Gumroad receipt and also include your key so I can take a look into it.

Thanks!

**Comment by dsihacker** [comment]
I forgot the support email, and I can't find the Gumroad receipt. can you send me the email?

**Comment by rugarciap** [comment]
Hi,

I can't pase it here, but you can find a support address inside the help file distributed with the app.

Best!

**Comment by dsihacker** [comment]
Where is the help file?
