### ISSUE TITLE
Black icon while run with root rights.

### ISSUE THREAD

**Issue by sstyle** [rugarciap/Turbo-Boost-Switcher#20]
Hi. The icon on the toolbar is black instead white when I launch the app with root rights from Terminal.

**Comment by rugarciap** [comment]
Hi!

Thanks for your feedback. Just tried it and all seems fine. Could you send more info please? Which OSX version are you using? 

Best!

**Comment by rugarciap** [comment]
Closing after no answer for almost a year.
