### ISSUE TITLE
Turbo Boost Switcher Pro asks every few minutes to enter the password

### ISSUE THREAD

**Issue by TremotinoVolante** [rugarciap/Turbo-Boost-Switcher#206]
Hi,

I bought the pro becouse I don't wanted to enter the password each time I open it. But Turbo Boost Switcher Pro asks to enter the password even more frequently than the free version. Like every time I open the charts and 10 to 15 times each day. It is really annoying. What I am doing wrong?

I'm using Turbo Boost Switcher Pro v2.13.0 and 13.6.7 (22G720) on a MacBook Pro 15" of 2017

I would be very happy for any help solving this issue.

**Comment by rugarciap** [comment]
Hi!

First of all, thanks for supporting! please, open the help section from the  menu and try the troubleshooting guide. If that doesn't help, reach me directly to the support email address provided for further help.

Best!

**Comment by TremotinoVolante** [comment]
> Hi!
> 
> First of all, thanks for supporting! please, open the help section from the menu and try the troubleshooting guide. If that doesn't help, reach me directly to the support email address provided for further help.
> 
> Best!

Thank you very much for your fast reply. 
I could solve the problem with the recipe 2.2 in the help section. Runs flawlessly!

Thank you!
