### ISSUE TITLE
Tempratures are not showing in Sonoma

### ISSUE THREAD

**Issue by guramrit-dhillon** [rugarciap/Turbo-Boost-Switcher#207]
I have a MacBook Pro 15-inch, 2019, with macOS 14.6.1, and I've been unable to make it work for a long time. The fan is always noisy, and the temperatures are not visible. I've tried almost all solutions I could find, e.g. running "csrutil disable" in recovery etc. Do you have any idea of what could be causing this?

<img width="318" alt="image" src="https://github.com/user-attachments/assets/7a59c1cb-ded7-455d-8613-91e8194840b1">

**Comment by rugarciap** [comment]
Hi! Just click over refresh rate to enable monitoring back again. Best!
