### ISSUE TITLE
Turbo boost not turning off

### ISSUE THREAD

**Issue by lolimjustherefornoreason** [rugarciap/Turbo-Boost-Switcher#208]
When i try to turn off turbo boost it just stays at on, how do i fix this?

**Comment by rugarciap** [comment]
Hi, please, follow the steps provided in the help option for troubleshooting. If that doesn't help either, reach me through support email provided for further support. Best.

**Comment by lolimjustherefornoreason** [comment]
> Hi, please, follow the steps provided in the help option for troubleshooting. If that doesn't help either, reach me through support email provided for further support. Best.

i got it to work thanks
