### ISSUE TITLE
[PRO] Turbo Boost state/rules are not preserved after wake up w/o login

### ISSUE THREAD

**Issue by toldo-27** [rugarciap/Turbo-Boost-Switcher#21]
When MacBook Pro (10.11.6) goes to sleep (lid is closed for 30 sec or so) the Turbo Boost is turned on right after waking up (automatic logout is disabled).

Free version (2.2.0) updates its status and and asks for a password to toggle defined state.

Meanwhile, Pro version says it is **Off** when it is actually **On**. 
It is set to correct state once you select **Enable/Disable Turbo Boost** option.
It is a bit annoying to toggle it manually each time Mac went asleep.

The app is great and it would be nice if daemon is polled and state is set according to app preference after system wakes up (I guess now it is done for login event and controlled by **Open at Login** setting).

**Comment by rugarciap** [comment]
Hi!

This page is just for free / open source version. Please, contact to the corresponding email from the web / gumroad platform for info about how to fix that (that has already been fixed).

Closing this.

Best regards and thanks.
