### ISSUE TITLE
[feature request] Option to always enable Turbo Boost when connected to power

### ISSUE THREAD

**Issue by cvskywalker** [rugarciap/Turbo-Boost-Switcher#22]
Would it be possible to get a option where Turbo Boost Switcher is aware of the power state, and will always enable when connected to AC, but remember the setting to switch to when running from battery?

Or should I do up a pull request for this?

**Comment by rugarciap** [comment]
Hi! This is included in the pro version (maybe in the fugure will be also included on the free one ;).

Best regards!
