### ISSUE TITLE
Add option to use less space in the menu

### ISSUE THREAD

**Issue by mrzv** [rugarciap/Turbo-Boost-Switcher#23]
It would be great if it was possible to make the menu bar entry narrower than it is now. For example, maybe instead of spelling out On/Off, it could change the color of the icon?

P.S. I bought the Pro version, so if you make it a paid feature, I'll be perfectly happy.

**Comment by rugarciap** [comment]
Will think about it, thanks for the suggestion! :)

**Comment by FELIXakaFX** [comment]
A temporary solution to this is just to rename the file icon.tiff in the Contents/Resources folder in the program to something different.

For example like this:
`mv /Applications/Turbo\ Boost\ Switcher.app/Contents/Resources/icon.tiff /Applications/Turbo\ Boost\ Switcher.app/Contents/Resources/icon.tiff.backup`

**Comment by rugarciap** [comment]
Just finishing up the current version, but the next one will include a setting to enable / disable that ;), both free and pro of course.

Thanks!
