### ISSUE TITLE
Can't disable CPU boost 2.3.0

### ISSUE THREAD

**Issue by AlexTeixeira** [rugarciap/Turbo-Boost-Switcher#24]
Hello,

I'm not able to switch boost to off since I updated to 2.3.0.

I have a macbook pro 13" 2015 installed with macOs Sierra.

<img width="582" alt="capture d ecran 2016-12-03 a 19 42 02" src="https://cloud.githubusercontent.com/assets/6555080/20861439/b5e8b6d2-b990-11e6-9ac4-1bf091e21a03.png">

**Comment by rugarciap** [comment]
Hi!

App works fine with that version, checked by me and many other users. Please, provide more info and attach some log, check your kext permissions, manually delete all files (or using tool like AppZapper) and reinstall, etc.

Best regards!

**Comment by AlexTeixeira** [comment]
Ok, After some investigation, only the manually switch doesn't work.

**Comment by rugarciap** [comment]
Hi,

Manual switch is the only option available for the free / open source version. If you wan't to comment something about the pro one, please, refer to the corresponding blog. That being said, manual switch processing is internally the same as auto one (on pro version), the only difference is when that is launched depending on the settings configured.

Best regards.
