### ISSUE TITLE
No longer works on 2016 MacBook Pro

### ISSUE THREAD

**Issue by drewbharris** [rugarciap/Turbo-Boost-Switcher#25]
I'm guessing something must have changed with the required register on the Skylake CPUs. I click "Disable Turbo Boost" and nothing happens.

Not sure if it's something that's fixable, but it would be sweet if it was! Thanks!

**Comment by rugarciap** [comment]
Hi!

Thanks for your feedback. 

MSRs on Skylake architecture instruction set regarding Turbo Boost are just the same as previous architectures (which is right; imagine having to change operating systems when a new processor is released :). You can take a look at the Intel's developer manual here:

http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developers-manual.pdf

> The 6th generation Intel® CoreTM processor family is based on the Skylake microarchitecture. They have CPUID DisplayFamily_DisplayModel signatures of 06_4EH and 06_5EH, supports the MSR interfaces listed in Table 35-18, Table 35-19, Table 35-23, Table 35-27, Table 35-33, Table 35-37, and Table 35-38

In table 35-18 you can see the register for enabling / disabling turbo boost is just the same as always: 1A0H41638 (which is the right thing to do)

Regarding your post, new macbooks come with macos sierra is installed by default. Please, take a look at this:

http://www.rugarciap.com/2016/08/how-to-run-turbo-boost-switcher-on-macos-sierra/

Closing the issue. 

Best regards!

**Comment by drewbharris** [comment]
You're totally right! Sorry about that!

**Comment by idoo** [comment]
short solution  — move this app outside `Download` dirrectory
