### ISSUE TITLE
Checkout does not produce valid VAT receipt

### ISSUE THREAD

**Issue by supersophie** [rugarciap/Turbo-Boost-Switcher#39]
Hi,

Tried to purchase but checkout process omitted VAT receipt with both mine and your VAT numbers.  Please advise. Thanks.

**Comment by rugarciap** [comment]
Hi,

You need to contact Gumroad's support for help since they sell the app through their systems, issue the invoices, etc.

Best.

Closing the question.

**Comment by supersophie** [comment]
Expect there is no method to contact Gumroad for buyers.

**Comment by rugarciap** [comment]
Just google "Gumroad support", first link ;).

Best regards.

**Comment by supersophie** [comment]
Thanks again.
