### ISSUE TITLE
Does not work with 10.12.6

### ISSUE THREAD

**Issue by woci** [rugarciap/Turbo-Boost-Switcher#40]
I can't turn off with the binary.
If I checkout the project and launch it, can't load the kext because of signature.

**Comment by rugarciap** [comment]
Hi,

The app works fine in that version as tried myself and reported from other users. You're for sure suffering from App Translocation as detailed here:

http://www.rugarciap.com/2016/08/how-to-run-turbo-boost-switcher-on-macos-sierra/

You can take a look into this too just if you want to play around by yourself with the kernel extension, but it's not needed anymore either:

https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html#//apple_ref/doc/uid/TP40016462-CH5-SW1

Closing.
