### ISSUE TITLE
Not working on Sierra.

### ISSUE THREAD

**Issue by dps999** [rugarciap/Turbo-Boost-Switcher#43]
Im trying to disable turbo boost but nothing changed.
Am i miss something or it doesn't work anymore?

**Comment by rugarciap** [comment]
Hi!

The app works fine on macOS Sierra, and even on recently released High Sierra. 

This has been answered on other posts.., you can take a lookt at this one in example :

https://github.com/rugarciap/Turbo-Boost-Switcher/issues/40

Best!

**Comment by rugarciap** [comment]
If you're using High Sierra, also take a look at this: https://www.rugarciap.com/2017/09/an-update-after-macos-high-sierra-release/

**Comment by cAstraea** [comment]
Also does nothing for me I'm on 10.12.6 Sierra , early 2013 macbook pro retina. The labels stays the same

**Comment by rugarciap** [comment]
http://www.rugarciap.com/2016/08/how-to-run-turbo-boost-switcher-on-macos-sierra/
