### ISSUE TITLE
Can't download update from wife's mac book

### ISSUE THREAD

**Issue by heaven** [rugarciap/Turbo-Boost-Switcher#44]
Hi, I don't remember how did I purchase the second license for my wife, perhaps I purchased both from my own mac. Now, when I am trying to download an update from wife's mac it proposes me to make a purchase, no download link.

**Comment by rugarciap** [comment]
HI!

This repository is meant for tbs open source and its issues. Please, contact me by answering to the update email with the problem.

In any case, just use the same binary (.dmg downloaded) on any other computer and enter the key.., will work ;)

Best!
