### ISSUE TITLE
Turbo does not turn off 

### ISSUE THREAD

**Issue by realies** [rugarciap/Turbo-Boost-Switcher#46]
On a rMBP Mid 2014 with 10.13 (17A405) disabling turbo boost still allows i7-4980HQ to go beyond 2.80GHz. Any clues?

**Comment by rugarciap** [comment]
Hi!

This is not a support forum, is an issue tracker, and there is no one reported, nor steps to reproduce, etc.

In any case, please, just take a look at other issues, README, faqs at blog (rugarciap.com/faqs). There is plenty of info about how to check what is going wrong, how to run the app on sierra, disabling SIP, translocation, etc.

Thanks for using the app!

If you find any additional info with more specific info (logs, kext status, steps to reproduce, etc) please don't hesitate and open another issue if you're unable to run the app after reviewing all the info mentioned above.
Best regards.

**Comment by realies** [comment]
@rugarciap, apologies for the lack of details.

I am running Turbo Boost Switcher from the Applications folder and have allowed it to execute within the Security & Privacy preferences. SIP is disabled.

I am monitoring the frequency via the [Intel Power Gadget](https://software.intel.com/en-us/articles/intel-power-gadget-20) (you might be interested including it in your manual).

I have just noticed where my confusion comes from. When the app is enabled, turbo is on, when disabled, turbo is off. Wouldn't it be more sensible for turbo to be off when the app is active and for it to go on when the app is inactive?
