### ISSUE TITLE
Mac OS 10.14 beta

### ISSUE THREAD

**Issue by etadzeta** [rugarciap/Turbo-Boost-Switcher#52]
Unable to switch Turbo Boost off, nothing happens.
Using Pro version 2.7.0

**Comment by rugarciap** [comment]
Hi!

Thanks for your feedback.

This is for open source / free version issues, not PRO, but in any case, beta was released a few hours ago! :)

In the following days / weeks the app will be tested against the betas Apple will be releasing so the app is ready when the final version of macOS 10.14 is released this fall. 

Stay tuned to the blog for updates regarding the betas.

Best!
