### ISSUE TITLE
Mojave?

### ISSUE THREAD

**Issue by MacDragon** [rugarciap/Turbo-Boost-Switcher#56]
Seems to be currently broken on Mojave beta at least for me, doing nothing when try to enable.

**Comment by rugarciap** [comment]
Hi,

Mojave is still beta and therefore contains bug, one of them is on kexutil app used to load kernel extensions. There are other popular kexts not working either. If Apple doesn't fix it in the future will release and update with a workaround before final release of Mojave is made.

Best!

**Comment by rugarciap** [comment]
Running fine on macOS Mojave Public Beta 3 after Apple fixing their issues.

**Comment by MacDragon** [comment]
Good to hear!, Was indeed  mainly wondering at what level the issue was and whether to expect it to work before release or not.

**Comment by rugarciap** [comment]
You can take a look at this for more info https://forums.developer.apple.com/thread/104675
