### ISSUE TITLE
Not working on macOS Mojave

### ISSUE THREAD

**Issue by fmichenaud** [rugarciap/Turbo-Boost-Switcher#58]
Hey, I've been trying the new macOS beta for a few days and it seems that Turbo Boost Switcher is not working on it.
The app launches, but disabling turbo boost doesn't trigger anything.

**Comment by rugarciap** [comment]
Duplicated #56

**Comment by rugarciap** [comment]
Running fine on macOS Mojave Public Beta 3 after Apple fixing their issues.
