### ISSUE TITLE
Show fan speed on 2018 MacBook 13"

### ISSUE THREAD

**Issue by rgaufman** [rugarciap/Turbo-Boost-Switcher#59]
Presently the latest version does not show the fan speed on the new 2018 MacBooks, but TurboBoost can be successfully disabled:

<img width="462" alt="screen shot 2018-07-15 at 16 16 27" src="https://user-images.githubusercontent.com/33842342/42735375-7c758738-884a-11e8-835a-a2c5f27aa78b.png">

**Comment by rugarciap** [comment]
Wow, that was fast! :) considering the first units were received yesterday on many Apple Stores!

In any case, thanks for your feedback.

Fan speed is displayed using Apple SMC Api and with generic names for fans, cpu ids, etc, so it should work...:| . In any case, will stay tuned just in case they've changed something. If you are able to send some will be cool too. You can try other apps that also uses SMC Api to check and post here the results, like smcFanControl app..., that'd help ;).

P.D: Later this year for holidays I hope to grab one of those and test for myself :).

**Comment by rgaufman** [comment]
Ah, yes, it seems to show some weird numbers with SMCFanControl:
<img width="232" alt="screen shot 2018-07-16 at 08 08 13" src="https://user-images.githubusercontent.com/33842342/42746377-725f78be-88cf-11e8-9167-bd4046dbe891.png">

I'm happy to share logs, but not sure which ones?

**Comment by rugarciap** [comment]
Thanks! no worries, knowing that smcFanControl doesn't display fan speed either is enough...

Stay tuned for future updates on this ;).

**Comment by freddedotme** [comment]
It seems like the fan number only would show if they were actually running. “N/A” in my case means that the fans must be idle since when I ran something heavier it all of a sudden showed a RPM number. You can ignore my issue (#60).

**Comment by rugarciap** [comment]
Hi again!

Could you please try with this tool and post here the results? Is this one: https://github.com/theopolis/smc-fuzzer

[smc.zip](https://github.com/rugarciap/Turbo-Boost-Switcher/files/2229540/smc.zip)

Just unzip and from command line type: `./smc -f` and post here the results. If possible, a dump would be great too `./smc -l > dump.txt`

Thanks!

**Comment by dzaiats** [comment]
Hi there!
MacBook Pro 2018, max configuration.

Please, find attached dump.txt
[dunp.txt](https://github.com/rugarciap/Turbo-Boost-Switcher/files/2236854/dunp.txt)

**Comment by rugarciap** [comment]
Great, thanks! Could you please also execute ./smc -f and post here the results!?

**Comment by dzaiats** [comment]
Sure!
Here it is
[dump.txt](https://github.com/rugarciap/Turbo-Boost-Switcher/files/2236865/dump.txt)

**Comment by dzaiats** [comment]
Probably I need to run something heavy and take a dump?

**Comment by dzaiats** [comment]
[dump-f-heavy.txt](https://github.com/rugarciap/Turbo-Boost-Switcher/files/2236878/dump-f-heavy.txt)
[dump-l-heavy.txt](https://github.com/rugarciap/Turbo-Boost-Switcher/files/2236879/dump-l-heavy.txt)

I have just executed the same commands during the building of heavy Android project

**Comment by rugarciap** [comment]
Thanks again!

Well, as I though, now all SMC info is being encrypted by new Apple T2 chip, and for some reason (still unknown) the info is not being displayed properly. Look at the output:

Total fans in system: 2

Fan #0:
    Actual speed : 11502417 Key[F0Ac]
    Minimum speed: 465
    Maximum speed: 224849
    Safe speed   : 0
    Target speed : -261295
    Mode         : auto

Fan #1:
    Actual speed : -11329391 Key[F1Ac]
    Minimum speed: -367
    Maximum speed: -496943
    Safe speed   : 0
    Target speed : 262353
    Mode         : auto

As you can see, the speeds are just wrong! Same happens with other apps using SMC to read fan speeds, like smcFanControl. 

Will investigate with the dump until I can grab a new Macbook 2018 for myself..., until then any help is appreciated!

Thanks!

**Comment by rugarciap** [comment]
By the way, as you can see on smc.h and SystemCommands.m, both fans (F0Ac and F1Ac) are the same that are being readed by the app:

#define SMC_KEY_FAN0_RPM_CUR  "F0Ac"
#define SMC_KEY_FAN1_RPM_CUR  "F1Ac"

**Comment by rugarciap** [comment]
Removed comment due to support question not related with the issue. There is plenty of info around about running the app the first time (Translocation & Kext authorization).

**Comment by Poopi** [comment]
Was about to buy Pro version when I discovered the problem with Fan readout.

Fan fields types from SMC has been changed on MBP2018.
See:
bash-3.2$ ./smc -l | grep F0
  F0Ac  [flt ]  (bytes 9b 3a 29 45)
  F0Dc  [flt ]  (bytes 45 08 90 3e)
  F0Fb  [ui8 ]  1 (bytes 01)
  F0Fc  [ui16]  4 (bytes 00 04)
  F0Md  [ui8 ]  0 (bytes 00)
  F0Mn  [flt ]  (bytes 00 00 07 45)
  F0Mx  [flt ]  (bytes 00 38 b9 45)
  F0Sf  [ui16]  0 (bytes 00 00)
  F0St  [ui8 ]  5 (bytes 05)
  F0Tg  [flt ]  (bytes 00 30 29 45)

Attached patch solves the issue....

[TBS_MBP2018.txt](https://github.com/rugarciap/Turbo-Boost-Switcher/files/2274044/TBS_MBP2018.txt)

**Comment by rugarciap** [comment]
Great! thanks for your feedback :). Unfortunately, I can't test that myself yet because my MBP 2018 will arrive in 2 weeks (it's not a default config one)...., but will probably compile and release a nightly build this weekend (not updatable) just in case some others want to test that too until an update is released containing the fix for this and a couple of other things too.

**Comment by rugarciap** [comment]
Other projects are updating just the same :)

In example: 

https://github.com/Chris911/iStats/blob/master/ext/osx_stats/smc.c

**Comment by rugarciap** [comment]
Just received my 2018 MBP!! :), Hope to release an update with this fix and a couple more in few days :).

**Comment by rugarciap** [comment]
Just released the 2.7.1 update with some additional fixes ;). Thanks to all for your feedback
