### ISSUE TITLE
Show fan speed on 2017 Macbook 13"

### ISSUE THREAD

**Issue by freddedotme** [rugarciap/Turbo-Boost-Switcher#60]
When I use TBS Pro the fan speed just says "N/A".
I use a MacBook Pro 13" 2017 with no Touch Bar running High Sierra 10.13.6.

**Comment by rugarciap** [comment]
Add the info to #59 please.., including some logs / screenshots and if possible a capture of other app that uses also SMC to read fan speeds (like smcFanControl) since those Macs have been around for long with any issues.
