### ISSUE TITLE
Pro Version Licensing Down?

### ISSUE THREAD

**Issue by atutrone** [rugarciap/Turbo-Boost-Switcher#62]
Unsure if this is the right spot to post issues with pro version.  Just purchased a license and trying to register but keep getting an error: 
```
Ooops! :(

Network connection problems. Please check your Internet connection and try again
```

Network connection is fine.  Tried on a few different connections.

**Comment by rugarciap** [comment]
Hi, this is for issues on open source version of Turbo Boost Switcher. For support questions about PRO versions, write answering to your receipt email. Thanks.

**Comment by rgaufman** [comment]
I never received a receipt, but I was charged for the software, can you please provide a support email?
