### ISSUE TITLE
Not all translation is working

### ISSUE THREAD

**Issue by rbukovansky** [rugarciap/Turbo-Boost-Switcher#66]
Hi,
I have found out, that translations of `menuCharting` and `sliderRefreshTimeLabel` are not working.

![screen shot 2018-08-02 at 10 42 38](https://user-images.githubusercontent.com/1004491/43573256-9dbd842c-9641-11e8-8786-710addbeeeec.png)

And are we able to get the translation for `CPU Load`, `rpm` texts?

Thank you.

**Comment by rbukovansky** [comment]
@rugarciap OK. Those `CPU load`, `rpm` are not critical...

BTW Have you had chance to review my PR with Czech translation? I just hope I haven't screwed up. Well, it worked on my Mac... Thanks.

**Comment by rugarciap** [comment]
Hi!

Yes, I saw that..., thanks! All translations were made by an external company thanks to all users who contributed getting the PRO, and will probably ask them to translate all to Czech too. I have no clue of Czech :S, but will use your contribution to make a double check on the work they send back for sure.

Thanks!

**Comment by rbukovansky** [comment]
@rugarciap If you want, I can do that translation even for Pro for you for free...

**Comment by rugarciap** [comment]
Fixed on 2.7.1..., new translations arriving on next version ;).
