### ISSUE TITLE
There is only one problem...

### ISSUE THREAD

**Issue by adanosX** [rugarciap/Turbo-Boost-Switcher#70]
In my MBP in windows 10 using Throttlestop etc., when disabling Turbo this leads to the CPU not having dynamic clocking anymore. 

Essentially by disabling Turbo, the base clock becomes the only clock, locks multiplier, and that's it.
its called LOCKED to base frequency.

Enabling Turbo not only increases cpu multiplier and frequency when there is demand, but also and more importantly is the same dynamic ability that drops multiplier frequency, reduces multiplier and has the initial features of "Haswell" onwards for "8h - all day battery" on mobile/laptops for Intel.

What I am saying is its impossible the CPU is cooler at idle or normal by disabling turbo especially in non-demanding (low to medium tasks, Turbo was created exactly for these tasks), its impossible to extract more power than with Turbo ON for any power users (like editing, etc.) since it takes more time to process. 

SO
With Turbo: 
+ Optimised to perform either when demanded or during idle (any user task).
+ Focus on user experience

In comparison: the computer reacts to user demand specifically, which can be demonstrated by peaks and troughs of productivity from high on high demand tasks to low until 0. The computer pushes the envelope for the system intended use as designed by the manufacturer.

Without Turbo: enough power   
+ Constant base clock means a non-optimised locked energy consumption regardless of user task demand
+ Focus on reducing quality of experience, compatibility of hardware and long-term issues associated to preserve longevity when in fact you kill the cpu anyway....

**Comment by adanosX** [comment]
https://marco.org/2015/06/07/disabling-turbo-boost

I don't know, actually I think any sacrifice to performance is too much of a sacrifice. 

If you have issues with the battery or something buy a new one is 70 bucks OEM. I can't think of any reason why to force the computer at base clock by disabling turbo than not.

Show me with evidence that the cpu frequency is still dynamic with your app in macOS having disabled Turbo and I will send you a gift.

**Comment by adanosX** [comment]
https://volta.garymathews.com

**Comment by adanosX** [comment]
Latest i9 VRMs issue
https://www.reddit.com/r/macbookpro/comments/91256u/optimal_cpu_tuning_settings_for_i9_mbp_to_stop/

**Comment by rugarciap** [comment]
With turbo boost disabled, no constant frecuency anywhere ;)..., just monitoring with Intel Power Gadget and TB off.

![image](https://user-images.githubusercontent.com/3028855/44006282-41032338-9e82-11e8-9371-29a8f002dd54.png)

In the other hand, this is not a forum, is for reporting issues. Thanks for your comments and opinion, but closing.
