### ISSUE TITLE
Failed update to Turbo-Boost-Switcher Pro v2.7.1

### ISSUE THREAD

**Issue by JulyIGHOR** [rugarciap/Turbo-Boost-Switcher#73]
Hello. Pro version updating is pain.
App itself can't find updates and gives no error dialogs on menu "check for update" pressed.
I just got email that new version v2.7.1 available, but I can't find download url anywhere.
Even if I login to gumroad website, I can find only 2.7.0 version.
Please do automatic update, or at least send download url to emails when released.

**Comment by rugarciap** [comment]
This is for reporting issues, not feature request and not a support platform. In any case, just let you know logs shows all pro users are updating fine from within the app, and there is also a [how to update ](KdOeJieL2.8HemcHdkwWdfWP1653)page just in case clicking on "Download" is not usable enough.

**Comment by JulyIGHOR** [comment]
I told you already, I'm pressing Download button on "how to update" page and its 2.7.0
"pro users are updating fine from within the app" It is my bug report. As I said already, pressing "Check for update" doing nothing in app menu.

**Comment by rugarciap** [comment]
As of tbs update page, if you want automatic download, you need to update first to 2.7.0.

**Comment by JulyIGHOR** [comment]
I'm already on 2.7.0, can't update to 2.7.1

**Comment by JulyIGHOR** [comment]
Ok I found a bug I think. There is dialog of update. But it behind all windows, so I didn't see it.

**Comment by JulyIGHOR** [comment]
Maybe it is good idea to make this dialog on top of all windows.
My issue fixed any way, I know how to update next time (search window behind others) thanks for support.

**Comment by rugarciap** [comment]
Can't open a modal from an app on status bar..., at least it doesn't work and I tried multiple methods in the past. Will consider try again in the future just in case.

Best.
