### ISSUE TITLE
Does not work on Mojave

### ISSUE THREAD

**Issue by tiberiusferreira** [rugarciap/Turbo-Boost-Switcher#78]
Hello, thanks for the App.

However, after clicking disable turbo boost it prompts for the password and then does nothing.

It still shows On.

There is no request to allow kernel extensions as seen below.

<img width="683" alt="screen shot 2018-09-29 at 16 49 26" src="https://user-images.githubusercontent.com/5420615/46249916-b37e1580-c407-11e8-99a6-0baaa42581e9.png">

What can I do to help debugging?

**Comment by rugarciap** [comment]
Hi,

Before opening an issue, please remember to check the faqs and posts on the blog, there is plenty of info around (translocation, kernel extension pre-aproval, etc).

The app works fine on Mojave, both free and pro, as tested by me and many other users. You're probably suffering from translocation and/or missed some step when installing.

You can take a look at this.

https://www.rugarciap.com/faqs/
https://www.rugarciap.com/2017/09/an-update-after-macos-high-sierra-release/
https://developer.apple.com/library/archive/technotes/tn2459/_index.html

Best.

**Comment by shortyadamk** [comment]
I had this same problem and solved it, I had been running the program directly from the download folder. After I dragged the file into the applications folder it worked as it was supposed to. Thanks!
