### ISSUE TITLE
Can't Disable Turbo Boost

### ISSUE THREAD

**Issue by Steffen888** [rugarciap/Turbo-Boost-Switcher#79]
I Just downloaded the free Version of the Turbo Boost Switcher to give it a try, as I am immensely disappointed with the battery life on heavy usage. 
Anyway, I opened the application and dragged it into the Applications folder, allowed the app in the Privacy Settings. 
It shows up in the top bar, but nothing happens when i click ´disable turbo boost´. I tried reinstalling the app, but nothing. I also enter the password to let TBS make changes, nothing. It always lets me click 'Disable turbo boost' again with no visible change. In the charts I can also see that it is not disabled. 

I have Macbook pro 15 inch (2018) with base config. 
Any help would appreciated.

**Comment by rugarciap** [comment]
Please, take a look at this, you probably missed the kext authorization.

https://github.com/rugarciap/Turbo-Boost-Switcher/issues/78

Thanks.

**Comment by prko** [comment]
Hello, 

I installed the free version on
- MacBook Pro 2014 15" and

**Comment by rugarciap** [comment]
Hello, 

Please, contact my email address (it's in the faqs) for support. There is no problem with any Macbook having Turbo Boost neither macOS version, including Big Sur current beta

Regards..
