### ISSUE TITLE
MacBook Air (13-inch, Early 2015) change mode fail

### ISSUE THREAD

**Issue by kalsolio** [rugarciap/Turbo-Boost-Switcher#80]
![jietu20181101-144640](https://user-images.githubusercontent.com/14342288/47836936-125af400-dde5-11e8-8268-ae27366ac7e6.jpg)
![jietu20181101-144719](https://user-images.githubusercontent.com/14342288/47836937-12f38a80-dde5-11e8-8d7a-22c8327f716c.jpg)
![jietu20181101-144725](https://user-images.githubusercontent.com/14342288/47836938-12f38a80-dde5-11e8-8667-963a87c301f7.jpg)

**Comment by rugarciap** [comment]
This has nothing to do with the app.
