### ISSUE TITLE
iMac i7 7700k 4.2GHz

### ISSUE THREAD

**Issue by ageorgios** [rugarciap/Turbo-Boost-Switcher#81]
Does anyone have tried it on an iMac i7 7700k 4.2GHz and show us Geekbench results?

The 4.2 turbo boosts to 4.5GHz, does this mean that the decrease in performance is ~10% because it clocks 0.3GHz lower? Or is it going to be more?

Will I get >20oC temperature drop or not?

**Comment by rugarciap** [comment]
Hi!

That depends on the tasks you're doing, since freq will vary depending on the needs. I recommend you to use Intel Power Gadget to monitor CPU freq.

Regards.
