### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [rugarciap/Turbo-Boost-Switcher#89]
i've downloaded Version '2.7.1' but when selecting it in the Finder and using 'Get Info' it claims to be Version '1.0'

the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are broken ( https://github.com/rugarciap/Turbo-Boost-Switcher/blob/master/Turbo%20Boost%20Disabler/Turbo%20Boost%20Switcher-Info.plist )

**Comment by rugarciap** [comment]
Hi, 

thanks for reporting, I know :), it's been like that since first version..., will sync in the upcoming 2.8.0 version about to be released.

Best!

**Comment by core-code** [comment]
awesome, thanks ;)
