### ISSUE TITLE
Free and Pro versions doesn't work with kext signing enabled

### ISSUE THREAD

**Issue by jjckswitch** [rugarciap/Turbo-Boost-Switcher#90]
I installed the program, launched it, pushed Turbo Boost off, entered the password, enabled the kext installation in security settings, and nothing happens. I tried disabling SIP - it helped, also works with csrutil enable --without kext
macOS 10.14.2, MacBook Air 2018.

**Comment by rugarciap** [comment]
Read the faqs on the blog and/or write to the support email, again, github project is not for this.
