### ISSUE TITLE
The program shows the CPU Proximity temperature, not the CPU temperature.

### ISSUE THREAD

**Issue by jjckswitch** [rugarciap/Turbo-Boost-Switcher#92]
The real temperature of the processor can be much higher than that of the CPU Proximity
![2019-01-04 18 40](https://user-images.githubusercontent.com/30491079/50691116-80c06a80-1051-11e9-9c61-2f6c21e16430.png)

**Comment by rugarciap** [comment]
Again, false, the app displays the core temprature using SMC api, same like other apps does.
