### ISSUE TITLE
Asks for password three times each time I wake computer from sleep

### ISSUE THREAD

**Issue by aaronraimist** [rugarciap/Turbo-Boost-Switcher#94]
Each time I wake my 2016 MBP it asks for my password (possibly the same as #4?). If I hit cancel it asks two more times before it gives up and stops asking. Turbo boost stays disabled the entire time so I'm not sure why it keeps asking for the password.

**Comment by rugarciap** [comment]
Yes, it's the same reason. That's because after a long sleep period, Turbo Boost is enabled again by OSX internally and if configured so, the app needs to disable Turbo Boost again by itself. It's explained also on other old posts.

Best regards.

**Comment by aaronraimist** [comment]
@rugarciap but in your answer in #4 you said

> What has been done on version 1.2 was to remove the need of entering the password each time the computer comes back from sleep, and storing it per session so the user needs to enter it once.

this seems like a regression since it is doing that again?

**Comment by rugarciap** [comment]
It's not.., it's just the way the authentication api and osx works. Read the comments to other issues, it's all there. If you've got any additional doubts you can write me to my contact address, since this is for reporting issues, not a support platform.

Best.
