### ISSUE TITLE
Did not compile on Mojave 10.14.4

### ISSUE THREAD

**Issue by aditya7fb** [rugarciap/Turbo-Boost-Switcher#97]
When I click the 'play' button in XCode I get the following error message:

Showing Recent Messages
:-1: No signing certificate "Developer ID Application" found: No "Developer ID Application" signing certificate matching team ID "xxxxxxxxxx" with a private key was found. (in target 'Turbo Boost Switcher')

**Comment by rugarciap** [comment]
Hi,

The app compiles fine, you need to customise the build settings for your environment as with any other Mac application.
